### ISSUE TITLE
Ad with duration <=5 seconds stay frozen and the player switch to the main content

### ISSUE THREAD

**Issue by ghost** [amzn/exoplayer-amazon-port#101]
### Issue description
When any Ads that have duration <= 5 seconds plays, the first frame is shown but stay frozen and automatically the player switch to the main content. 

The expected behaviour should play the advert normally. It's possible to play any Ads that duration is greater than 5 seconds, that's a really weird bug.

We've tested using your sample app and the Exoplayer sample-app as well, the same behaviour in both cases.

We've used the same manifest to play as the main content and the manifest plays fine.

### Reproduction steps
- For this example, We've set the Advert as `PRE-ROLL`.
- Just open the App and you will see the frame frozen and after 2 seconds, the main content starts playing fine. (Considering that you will use your Amazon sample app)

### Link to test content
This is the APK that you can test it
https://www.dropbox.com/s/ysmpx23ufkfqb98/demo-ima-debug.apk?dl=0

### A full bug report captured from the device
[bugreport-NS6271-2020-03-04-19-33-41.zip](https://github.com/amzn/exoplayer-amazon-port/files/4292493/bugreport-NS6271-2020-03-04-19-33-41.zip)

### Version of ExoPlayer being used
Using version 2.10.8

### Device(s) and version(s) of Android being used
- Amazon FireTV stick with Fire OS 6.2.6.8 | Fire TV Home Version 6210051.1
- Amazon FireTV stick 4K with Fire OS 6.2.6.8 | Fire TV Home Version 6210051.1

**Comment by ghost** [comment]
This is the video reproducing the problem
[IMG_2543.webm.zip](https://github.com/amzn/exoplayer-amazon-port/files/4292535/IMG_2543.webm.zip)

**Comment by aditya-gu** [comment]
Hi @sky-uiltonsantos ,
Thanks for the A2A.
We have released version 2.11.3 of ExoPlayer with Amazon changes. Could you please check if the issue is reproduced with this version as well?
Also could you please confirm the FireOS version of Amazon FireTV stick where the issue is reproduced?

**Comment by ghost** [comment]
> Hi @sky-uiltonsantos ,
> Thanks for the A2A.
> We have released version 2.11.3 of ExoPlayer with Amazon changes. Could you please check if the issue is reproduced with this version as well?
> Also could you please confirm the FireOS version of Amazon FireTV stick where the issue is reproduced?

Hi, We used these two devices here:
- Amazon FireTV stick with Fire OS 6.2.6.8 | Fire TV Home Version 6210051.1
- Amazon FireTV stick 4K with Fire OS 6.2.6.8 | Fire TV Home Version 6210051.1

Is this information is enough for you?

**Comment by aditya-gu** [comment]
Yes. Thanks for the information.. :)
We're looking into this issue. We'll keep you updated.

**Comment by ghost** [comment]
Hey @aditya-gu the issue still happens on the version 2.11.3.
This issue happens on the Exoplayer as well. 
Any luck with the investigation? Can you reproduce on your ends?

**Comment by hunterkill3r** [comment]
Hi @aditya-gu Have you had much luck with this issue?

**Comment by aditya-gu** [comment]
Hi,
We are able to reproduce the issue at our end. We're working on it.

**Comment by hunterkill3r** [comment]
Hi @aditya-gu Have you got an update on your end for this issue? 
Many thanks!

**Comment by aditya-gu** [comment]
Hi,
We're working on this issue. We'll be updating this ticket with our findings.
Thanks for patience. :)

**Comment by sky-filipeuva** [comment]
A sample Ad manifest url that fails : `https://mssl.fwmrm.net/m/1/171224/34/6297762/CK17122H_ENT_MEZZ_HULU_1783428_621/CK17122H_ENT_MEZZ_HULU_1783428_621.m3u8`

**Comment by aditya-gu** [comment]
Hi @sky-filipeuva ,
Thanks for the ad manifest URL.
We'll use this URL for debugging.

**Comment by ghost** [comment]
Any news so far @aditya-gu?
Do you need any more input from us?

**Comment by aditya-gu** [comment]
Hi @sky-uiltonsantos ,
We're working on it. We're making progress.
Apologies for lacking progress details, as this is something I am not allowed to share.

**Comment by ghost** [comment]
> Hi @sky-uiltonsantos ,
> We're working on it. We're making progress.
> Apologies for lacking progress details, as this is something I am not allowed to share.

Sure thing. Do you have any ETA for this?
